### PR TITLE
fix(package-manager): use PkgIdWithPatchHash in CasPathsByPkgId after #481

### PR DESCRIPTION
**Pull request by zkochan**
## Problem

CI on `main` is failing across every job (Doc, Dylint, Lint and Test on macos / ubuntu / windows) — see [run 25831190878](https://github.com/pnpm/pacquet/actions/runs/25831190878/job/75896265070). Two errors in `link_hoisted_modules.rs`:

```
error[E0277]: the trait bound `String: Borrow<PkgIdWithPatchHash>` is not satisfied
   --> crates/package-manager/src/link_hoisted_modules.rs:255:56
255 | let Some(cas_paths) = opts.cas_paths_by_pkg_id.get(&node.pkg_id_with_patch_hash) else {

error[E0308]: mismatched types
   --> crates/package-manager/src/link_hoisted_modules.rs:260:37
260 |             pkg_id_with_patch_hash: node.pkg_id_with_patch_hash.clone(),
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `String`, found `PkgIdWithPatchHash`
```

Two recently-merged PRs collided:

- **#504 (`fa418507`)** — `PkgIdWithPatchHash` newtype replaces `String` in dep-graph nodes (`DependenciesGraphNode.pkg_id_with_patch_hash` field type).
- **#505 (`d5b33e75`)** — `linkHoistedModules` linker (#438 slice 5) consumes `pkg_id_with_patch_hash` as `String`. Both PRs passed CI individually but the merge order leaves the linker consuming the old shape against the new field type.

## Fix

Update the linker to follow the brand:

- `CasPathsByPkgId` becomes `HashMap<PkgIdWithPatchHash, _>` (was `HashMap<String, _>`). The brand exists for type safety per `CLAUDE.md`'s branded-string-types section — keying the map by the brand matches `DependenciesGraphNode.pkg_id_with_patch_hash` and keeps the `.get()` lookup statically correct.
- `LinkHoistedModulesError::MissingCasPaths.pkg_id_with_patch_hash` switches from `String` to `PkgIdWithPatchHash`. The error message format string changes from `{...:?}` (debug) to `{...}` (Display) since `PkgIdWithPatchHash` impls Display to print the underlying string verbatim.
- Three test sites updated to construct `PkgIdWithPatchHash` via `From<&str>` rather than `String`.

## Test plan

- [x] `just ready` — 1186/1186 pass (matches the `Lint and Test` CI job that's currently failing on main)
- [x] `cargo doc --workspace --no-deps` with `RUSTDOCFLAGS="-D warnings"` — clean (matches the failing `Doc` job)
- [x] `just dylint` — clean (matches the failing `Dylint` job)
- [x] `taplo format --check` — clean

---
Written by an agent (Claude Code, claude-opus-4-7).

## Summary by CodeRabbit

* **Refactor**
  * Internal improvements to package identification type system for enhanced type safety and consistency.

* **Tests**
  * Updated test coverage to reflect package identification system changes.

[Review Change Stack](https://app.coderabbit.ai/change-stack/pnpm/pacquet/pull/510)

### CODE REVIEW

**Comment by zkochan** [comment]
Closing as a duplicate — #508 (`72fb61bc`) landed the same fix earlier today. Same diagnosis (#504 + #505 merge collision), same resolution (`CasPathsByPkgId` keyed on `PkgIdWithPatchHash`, `MissingCasPaths.pkg_id_with_patch_hash` switched to the brand, three test sites updated to `PkgIdWithPatchHash::from(...)`).

I missed #508 when I looked at the failing run; should have re-checked main before opening. Apologies for the noise.

---
Written by an agent (Claude Code, claude-opus-4-7).
